INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'女装 /男装 /内衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'鞋靴 /箱包 /配件', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'童装玩具 /孕产 /用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'家电 /数码 /手机', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'美妆 /洗护 /保健品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'珠宝 /眼镜 /手表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'运动 /户外 /乐器', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'游戏 /动漫 /影视', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'美食 /生鲜 /零食', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'鲜花 /宠物 /农资', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'面料集采 /装修 /建材', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'家具 /家饰 /家纺', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'汽车 /二手车 /用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'办公 /DIY /五金电子', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'百货 /餐厨 /家庭保健', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,name, created_at, updated_at) VALUES (1,'学习 /卡券 /本地服务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,1,'女装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,1,'男装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,1,'内衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,2,'鞋靴', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,2,'箱包', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,2,'配件', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,3,'童装玩具', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,3,'孕产', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,3,'用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,4,'家电', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,4,'数码', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,4,'手机', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,5,'美妆', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,5,'洗护', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,5,'保健品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,6,'珠宝', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,6,'眼镜', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,6,'手表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,7,'运动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,7,'户外', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,7,'乐器', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,8,'游戏', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,8,'动漫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,8,'影视', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,9,'美食', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,9,'生鲜', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,9,'零食', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,10,'鲜花', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,10,'宠物', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,10,'农资', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,11,'面料集采', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,11,'装修', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,11,'建材', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,12,'家具', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,12,'家饰', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,12,'家纺', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,13,'汽车', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,13,'二手车', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,13,'用品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,14,'办公', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,14,'DIY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,14,'五金电子', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,15,'百货', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,15,'餐厨', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,15,'家庭保健', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,16,'学习', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,16,'卡券', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (2,16,'本地服务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'连衣裙', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'半身裙', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'毛针织衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'T恤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'短外套', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'卫衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'汉服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'JK制服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'LOLITA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'衬衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'百搭裤装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'裤裙', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'牛仔裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'西装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'大码女装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'时尚套装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'蕾丝衫/雪纺衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'风衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'休闲裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'背心吊带', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'马夹', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'牛仔外套', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'阔腿裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'中老年女装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'婚纱礼服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'民族服装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'打底裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'西装裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'唐装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,17,'旗袍', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'春夏新品', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'T恤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'衬衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'POLO衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'休闲裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'牛仔裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'套装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'外套', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'夹克', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'卫衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'风衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'西装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'牛仔外套', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'棒球服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'品质好物', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'皮衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'针织衫/毛衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'运动裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'工装裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'开衫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'马甲', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'毛呢大衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'羽绒服', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'棉衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'中老年', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'情侣装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'大码', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'民族风', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'专柜大牌', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'明星网红', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,18,'原创设计', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'法式内衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'无钢圈内衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'内裤女', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'文胸', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'内裤男', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'长袖睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'睡裙', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'真丝睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'丝袜', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'船袜', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'情侣睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'抹胸', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'背心', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'睡袍', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'男士睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'塑身衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'内衣套装', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'打底裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'连体睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'聚拢文胸', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'男士袜子', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'棉袜女', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'卡通睡衣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'无痕内裤', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO t_category (level,pid,name, created_at, updated_at) VALUES (3,19,'少女文胸', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
